### ISSUE TITLE
How do we best allow users to contribute? I think, move the documentation to files in the main repository.

### ISSUE THREAD

**Issue by roke-julian-lockhart** [GHolk/addy-io-unofficial#1]
How do we best allow users to contribute? I ask because, per [the undermentioned](https://stackoverflow.com/revisions/37776291/1#:~:text=Unless%20you%20are%20a%20%22marked%22,the%20wiki%20and%20edit%20it.):

> > Wikis can be edited directly on GitHub, or you can work with a text editor offline and simply push your changes. Wikis are collaborative by design. By default, only collaborators on your repository can make changes to wikis, but you can configure this to be enabled for all users on public repositories. [Source](https://help.github.com/articles/about-github-wikis/)
> 
> So, you can't make a PR to change a wiki. You need to be a collaborator unless the settings are such that anyone can make changes, in which case you can go directly to the wiki and edit it.

As an example, I want to correct myriad grammatical errors within lines like <a href="https://github.com/GHolk/addy-io-unofficial/wiki/Home/fb801a921770ece556f4c7e458871e1b383e602d#term:~:text=A%20website%20can%20has%20arbitratry%20kind%20of%20the%20following%20tags:">this</a>. However, I'm unable to access a source version and reference the line, nor create a PR to modify it.

Instead, I must either be authorised as a contributor, or I must locally clone the repository (and even then, probably wouldn't be able to push). Consequently, I suggest that we move the existing documentation to a `readMe.MD` file.

**Comment by GHolk** [comment]
I has disable the editing restriction on wiki.
(settings / general / features / wiki / Restrict editing to collaborators only)

**Comment by roke-julian-lockhart** [comment]
> https://github.com/GHolk/addy-io-unofficial/issues/1#issuecomment-2452005155

Much better, @GHolk. It works now.

**Comment by roke-julian-lockhart** [comment]
@GHolk, I dare say that this might need to be reconsidered when we have multiple authors submitting requests at the same time, since wikis don't accept PRs, and it would be trivial for multiple authors committing changes simultaneously to overwrite each others' modifications. That's been the rationale for https://github.com/google/open-location-code/issues/490#issue-1287707196.

**Comment by GHolk** [comment]
I don't think this will happen a lots.
